services:
  deepsock:
    build: .  # Build the image from the current directory (where this docker-compose.yml is)
    # Default command from Dockerfile will run deepsock.py
    # To run a different script, uncomment and modify the line below:
    # command: python some_other_script.py
    env_file:
      # Load environment variables from the .env file in the same directory
      # Make sure to create and configure your .env file before running
      - .env
    volumes:
      # Optional: Mount the .env file directly
      # This allows changing config without rebuilding the image
      # - ./.env:/app/.env:ro # :ro makes it read-only inside the container
    restart: unless-stopped # Restart the container unless explicitly stopped